spring.application.name=TildarMen

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/tildarmennewdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

auth.token.expirationInMils=6000000
auth.token.jwtSecret=8cca8e1d2913c0d4ed97795a409ba394caf0f3bec833904bedfd7566805ebf63b8dd5cc280b570676f3fed4a7872ee889051b2787c6e1bf9a73f84440e14c7a4
